project_id = "tkbivipqiewkfnhktmqq"

[functions.webhook-pagamento]
verify_jwt = false

[functions.imperio-api]
verify_jwt = false

[functions.whatsapp-api]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.openflow-ai]
verify_jwt = false

[functions.expert-research]
verify_jwt = false

[functions.facebook-ads-sync]
verify_jwt = false
