// Conteúdo inicial da biblioteca de estratégias (semeia imphq_playbooks / imphq_playbook_steps).
// Metas são pontos de partida para calibrar por projeto, não promessa. Variáveis: {projeto} {produto} {plataforma} {conta}.
import type { Playbook, PlaybookStep } from "./playbooks.ts";

type StepInput = Omit<PlaybookStep, "metrica" | "checklist" | "depende_de" | "skill"> & {
  skill?: string | null; metrica?: PlaybookStep["metrica"]; checklist?: string[]; depende_de?: number[];
};
const step = (s: StepInput): PlaybookStep => ({ skill: null, metrica: null, checklist: [], depende_de: s.ordem > 1 ? [s.ordem - 1] : [], ...s });

// Etapas de base que quase todo playbook usa.
const avatar = (ordem: number): StepInput => ({
  ordem, secao: "Preparação", label: "Avatar e dores de {produto}", kind: "doc", executor_type: "AI_SKILL", skill: "avatar-architect-v8",
  contrato: { o: "Garantir o avatar de {projeto} (dores, desejos, objeções, linguagem) como base de toda peça.", e: "Cadastro do projeto, conversas e comentários reais.", s: "Avatar atualizado no projeto.", p: "As facetas do avatar preenchidas e revisadas há menos de 30 dias.", m: "Facetas preenchidas; objeções reais incorporadas.", d: "Conversas ou pesquisa com o público.", f: "Mensal.", x: "Sem dado real, marcar o avatar como hipótese e não escalar verba em cima dele." },
  checklist: ["Avatar com as facetas preenchidas", "Objeções reais registradas"], depende_de: [],
});
const angulos = (ordem: number, depende: number[]): StepInput => ({
  ordem, secao: "Preparação", label: "Ângulos para testar", kind: "doc", executor_type: "AI_SKILL", skill: "angulos-criativos",
  contrato: { o: "Montar o banco de ângulos de {produto}: 1 ângulo × 1 sub-avatar por teste.", e: "Avatar, mecanismo e referências que escalam no mercado.", s: "5 ângulos com copy e brief de imagem.", p: "5 ângulos prontos e cada teste anterior com resultado registrado.", m: "Custo por resultado por ângulo.", d: "Avatar.", f: "A cada rodada de testes.", x: "Sem métrica do teste anterior, o ângulo fica como \"sem dado\", nunca como vencedor." },
  checklist: ["5 ângulos novos", "Resultado dos ângulos anteriores registrado"], depende_de: depende,
});

export const PLAYBOOK_LIBRARY: Playbook[] = [
  // ───────────── X1 (conversa) ─────────────
  {
    id: "x1-conversa", nome: "X1 — anúncio para conversa", familia: "x1_ads",
    resumo: "Anúncio que abre conversa no WhatsApp ou DM; a IA diagnostica, quebra objeções e envia o checkout; recuperação em 3 toques.",
    quando_usar: "Ticket médio ou alto, produto que precisa de explicação ou confiança, público que responde bem a conversa.",
    quando_evitar: "Sem número de atendimento ativo ou sem IA/time para responder em minutos.",
    horizonte: "7 dias para o primeiro veredito por ângulo.", north_star: "vendas",
    kpis: [
      { key: "conversas_x1", label: "Conversas novas", meta: "ajustar ao orçamento diário" },
      { key: "cpl", label: "Custo por conversa", meta: "definir na 1ª semana e cair 20% em 30 dias", unidade: "moeda" },
      { key: "vendas", label: "Vendas", meta: "1 venda a cada 10 a 20 conversas (referência inicial)" },
      { key: "vendas_com_origem", label: "Vendas com origem", meta: "acima de 80%", unidade: "percentual" },
    ],
    riscos: ["Número bloqueado por volume ou spam: limite de envios e no máximo 3 falhas antes de pausar.", "IA inventando preço ou link: usar só os cadastrados."],
    fonte: "imphq_funnel_templates:x1-dm-closer",
    steps: [
      step(avatar(1)),
      step(angulos(2, [1])),
      step({ ordem: 3, secao: "Aquisição", label: "Anúncio click-to-WhatsApp", kind: "meta_ads", executor_type: "HUMAN_OPERATOR", skill: "briefing-gestor-trafego",
        contrato: { o: "Trazer conversas qualificadas para o X1 de {produto}. A IA prepara criativo e texto; uma pessoa sobe e aprova.", e: "Ângulos, número de atendimento e mensagem inicial com a palavra do anúncio.", s: "Conversas novas com origem (ângulo e anúncio).", p: "Anúncio no ar com o nome padronizado e custo por conversa medido.", m: "Custo por conversa; conversas por dia.", d: "Ângulos; número de WhatsApp conectado.", f: "Contínua, revisão a cada 3 dias.", x: "Custo por conversa acima da meta por 3 dias: pausar o conjunto e trocar o ângulo." },
        metrica: { key: "cpl", meta: "definir na 1ª semana" }, checklist: ["Conta de anúncio ligada ao Império", "Mensagem inicial com a palavra do anúncio"] }),
      step({ ordem: 4, secao: "Conversão", label: "IA consultiva no X1", kind: "whatsapp", executor_type: "API_AUTONOMOUS",
        contrato: { o: "Responder em minutos, diagnosticar, quebrar objeções e enviar o link certo de {produto}.", e: "Mensagem do lead, avatar, mecanismo, produtos e links cadastrados.", s: "Lead qualificado com o link do checkout.", p: "Respostas saindo sem erro e conversas chegando ao Império com origem.", m: "Tempo de primeira resposta; % de conversas com link enviado.", d: "Instância de WhatsApp conectada; links no cadastro.", f: "Contínua.", x: "Pedido de humano, objeção grave ou 3 falhas: pausar a IA na conversa e chamar a equipe." },
        metrica: { key: "conversas_x1" }, checklist: ["Número conectado no Império", "Links de checkout cadastrados", "Regras de tom e oferta revisadas"] }),
      step({ ordem: 5, secao: "Conversão", label: "Checkout de {produto}", kind: "checkout", executor_type: "EXTERNAL_TOOL",
        contrato: { o: "Receber o pagamento preservando a origem da conversa.", e: "Link enviado na conversa com UTM do anúncio.", s: "Venda aprovada no Império pelo webhook.", p: "Venda chegando com origem em até 1 h.", m: "Vendas; % com origem.", d: "Webhook da plataforma de pagamento apontando para o Império.", f: "Contínua.", x: "Venda que não chega em 1 h: conferir o painel da plataforma e o webhook-pagamento." },
        metrica: { key: "vendas" }, checklist: ["Webhook da plataforma ligado", "UTM no link enviado pela IA"] }),
      step({ ordem: 6, secao: "Conversão", label: "Recuperação em 3 toques", kind: "recuperacao", executor_type: "API_AUTONOMOUS",
        contrato: { o: "Recuperar pix, boleto e carrinho abandonado com 3 toques (15 min, 2 h, 24 h).", e: "Aviso de pendência ou abandono da plataforma.", s: "Pagamento fechado ou lead marcado como perdido.", p: "Rotina ativa e vendas recuperadas registradas.", m: "Taxa de recuperação.", d: "Webhook de abandono/pendência; checkout.", f: "Contínua.", x: "No máximo 3 toques por pedido; depois disso, parar." },
        metrica: { key: "recuperadas" }, checklist: ["Aviso de abandono chegando ao Império", "Mensagens dos 3 toques aprovadas"], depende_de: [5] }),
      step({ ordem: 7, secao: "Medição", label: "Análise semanal do X1", kind: "ia", executor_type: "AI_SKILL", skill: "analise-criativos-escalados",
        contrato: { o: "Cruzar gasto, conversas e vendas por ângulo e decidir: escalar, pausar ou testar novo ângulo.", e: "Gasto (sync), conversas e vendas com origem.", s: "Decisão por anúncio e próxima rodada de ângulos.", p: "Toda campanha ativa com decisão registrada na semana.", m: "Custo por venda e ROAS por ângulo.", d: "Gasto sincronizado; vendas com origem.", f: "Semanal.", x: "Com menos de 80% das vendas com origem, a análise vale só como indício." },
        metrica: { key: "roas" }, depende_de: [3, 5] }),
    ],
  },

  // ───────────── Ads direto (DTC) ─────────────
  {
    id: "ads-direto-dtc", nome: "Anúncio direto — página e checkout", familia: "x1_ads",
    resumo: "Anúncio → pré-venda (advertorial, quiz ou VSL) → página de oferta → checkout com bump e upsell, tudo com origem medida.",
    quando_usar: "Produto físico ou digital de decisão rápida, oferta validada, checkout com upsell.",
    quando_evitar: "Sem pixel/CAPI e sem rastreamento de origem: não há como saber o que vende.",
    horizonte: "3 a 7 dias por teste de criativo; 14 dias para julgar página.", north_star: "roas",
    kpis: [
      { key: "roas", label: "ROAS", meta: "acima do ponto de equilíbrio da oferta" },
      { key: "cpa", label: "Custo por venda", meta: "abaixo da margem por venda", unidade: "moeda" },
      { key: "taxa_clique_checkout", label: "Clique para o checkout", meta: "referência inicial: 5% a 15% da página de oferta", unidade: "percentual" },
      { key: "vendas_com_origem", label: "Vendas com origem", meta: "acima de 80%", unidade: "percentual" },
    ],
    riscos: ["Marca de terceiros em peças e páginas: risco de reprovação e bloqueio da conta.", "Escalar sem origem da venda: decisão no escuro."],
    fonte: "imphq_funnel_templates:perpetuo-vsl",
    steps: [
      step(avatar(1)),
      step(angulos(2, [1])),
      step({ ordem: 3, secao: "Preparação", label: "Produção de criativos", kind: "processo", executor_type: "EXTERNAL_TOOL", skill: "angulos-criativos",
        contrato: { o: "Gerar 3 variações por ângulo (gancho 0–3 s, corpo, CTA) em imagem e vídeo; a IA escreve e a ferramenta renderiza.", e: "Ângulos e marca.", s: "Criativos nomeados por ângulo e sub-avatar.", p: "3 variações por ângulo prontas e aprovadas em compliance.", m: "Criativos prontos por rodada.", d: "Ângulos.", f: "Semanal.", x: "Peça com marca de terceiros ou promessa médica não sobe." }, depende_de: [2] }),
      step({ ordem: 4, secao: "Aquisição", label: "Campanha de teste (Meta)", kind: "meta_ads", executor_type: "HUMAN_OPERATOR", skill: "briefing-gestor-trafego",
        contrato: { o: "Testar 1 ângulo por conjunto com orçamento controlado. A IA prepara; uma pessoa aprova e sobe.", e: "Criativos, link com UTM, orçamento.", s: "Dados de CTR, CPC e CPA por criativo.", p: "Campanha no ar, gasto sincronizado no Império.", m: "CTR, CPC, CPA.", d: "Conta de anúncio ligada; pixel e CAPI.", f: "Contínua.", x: "Anúncio reprovado: ajustar a peça e registrar o motivo; não reenviar igual." },
        metrica: { key: "gasto_ads" }, checklist: ["Conta de anúncio sincronizada", "Pixel e CAPI disparando compra"] }),
      step({ ordem: 5, secao: "Conversão", label: "Pré-venda (advertorial, quiz ou VSL)", kind: "advertorial", executor_type: "AI_SKILL", skill: "lp-persuasiva-v2",
        contrato: { o: "Aquecer o tráfego frio e levar à oferta com a origem preservada.", e: "Tráfego do anúncio com UTM.", s: "Clique para a página de oferta.", p: "Página com tracker do Império, sem marca de terceiros e com clique medido.", m: "Taxa de clique para a oferta.", d: "Tracker instalado.", f: "Revisar a cada rodada.", x: "Sem tracker, não usar em teste novo." },
        metrica: { key: "sessoes_pagina" }, checklist: ["Tracker do Império com projeto", "Versão própria sem marca de terceiros"] }),
      step({ ordem: 6, secao: "Conversão", label: "Página de oferta de {produto}", kind: "pagina_vendas", executor_type: "AI_SKILL", skill: "lp-persuasiva-v2",
        contrato: { o: "Vender: oferta, prova, garantia e escolha do kit/plano.", e: "Visitante aquecido.", s: "Clique para o checkout com UTM, fbclid e ad_id.", p: "Clique para o checkout medido e origem chegando ao checkout.", m: "Taxa de clique para o checkout.", d: "Checkout.", f: "Revisar a cada 14 dias.", x: "Queda brusca de cliques: conferir o print da página antes de mexer na campanha." },
        metrica: { key: "taxa_clique_checkout", meta: "5% a 15% (referência)" } }),
      step({ ordem: 7, secao: "Conversão", label: "Checkout com bump", kind: "checkout", executor_type: "EXTERNAL_TOOL",
        contrato: { o: "Receber o pagamento com order bump e origem preservada.", e: "Link com UTM e parâmetros de afiliado.", s: "Venda aprovada no Império.", p: "Primeira venda aprovada com origem preenchida.", m: "Vendas; taxa de bump; % com origem.", d: "Webhook ligado.", f: "Contínua.", x: "Venda sem origem entra marcada para conferência, sem atribuir por palpite." },
        metrica: { key: "vendas" } }),
      step({ ordem: 8, secao: "Conversão", label: "Upsell pós-compra", kind: "upsell", executor_type: "EXTERNAL_TOOL",
        contrato: { o: "Aumentar o ticket logo após a compra.", e: "Comprador do produto principal.", s: "Venda do upsell.", p: "Upsell ativo e medido.", m: "Taxa de upsell.", d: "Checkout.", f: "Revisar mensalmente.", x: "Upsell quebrado não pode travar a entrega do principal." } }),
      step({ ordem: 9, secao: "Medição", label: "Análise e decisão de verba", kind: "ia", executor_type: "AI_SKILL", skill: "analise-criativos-escalados",
        contrato: { o: "Ler gasto e vendas por criativo e propor pausar, escalar ou novo ângulo; mudança de verba pede aprovação.", e: "Gasto sincronizado, vendas com origem.", s: "Ações por anúncio e próxima rodada de criativos.", p: "Decisão registrada para cada campanha ativa na semana.", m: "ROAS e CPA por ângulo.", d: "Gasto e vendas com origem.", f: "A cada 3 dias.", x: "Sem venda com origem, não escalar: só pausar o que gasta sem clique." },
        metrica: { key: "roas" }, depende_de: [4, 7] }),
    ],
  },

  // ───────────── Esteira de Escala DTC (anúncio direto) ─────────────
  {
    id: "esteira-escala-dtc", nome: "Esteira de Escala DTC — teste, rodada, escala e cemitério", familia: "x1_ads",
    resumo: "Método de verba para anúncio direto: P1 testa concepts (ângulo + avatar) pelo custo por checkout iniciado, P2 valida o texto vencedor pelo CPA, P3 escala com bid cap e P4 guarda ângulos secos em cost cap. Cada fase tem regra de veredito.",
    quando_usar: "Oferta já validada com pixel/CAPI medindo checkout iniciado e compra, e payout e CPA alvo conhecidos. Complementa o playbook 'Anúncio direto — página e checkout'.",
    quando_evitar: "Sem checkout iniciado medido (o P1 decide por ele) ou sem verba para 2 dias de teste sem mexer.",
    horizonte: "P1 em 2 dias, P2 em 3 dias; P3 e P4 contínuos.", north_star: "cpa",
    kpis: [
      { key: "custo_por_ic", label: "Custo por checkout iniciado (P1)", meta: "até CPA alvo ÷ ICs por venda", unidade: "moeda" },
      { key: "cpa", label: "CPA", meta: "até o CPA alvo (zona ESCALA)", unidade: "moeda" },
      { key: "roas", label: "ROAS", meta: "acima de payout ÷ CPA alvo" },
      { key: "vendas", label: "Vendas", meta: "crescer com o CPA na zona ESCALA ou LUCRATIVA" },
    ],
    riscos: [
      "Mexer em verba e lance no mesmo dia: perde a leitura do que mudou.",
      "Julgar antes do dia 2 (P1) ou do dia 3 (P2): mata concept bom por pouco dado.",
      "Repetir hipótese refutada com criativo novo: queima verba no mesmo erro.",
    ],
    fonte: "AffHub — metodologia DTC Affiliate (@gbifi); regras em _shared/scale-ladder.ts",
    steps: [
      step(avatar(1)),
      step(angulos(2, [1])),
      step({ ordem: 3, secao: "Preparação", label: "Parâmetros da esteira de {produto}", kind: "doc", executor_type: "HUMAN_OPERATOR", depende_de: [],
        contrato: { o: "Definir payout (quanto entra por venda), CPA alvo e checkouts iniciados por venda de {produto}: deles saem todos os tetos e lances.", e: "Preço, comissão ou margem e histórico de conversão do checkout.", s: "Payout, CPA alvo e ICs por venda registrados nas notas da etapa.", p: "Os 3 números registrados e conferidos por alguém do time.", m: "Breakeven, ROAS alvo, teto de custo por IC.", d: "Oferta e checkout definidos.", f: "Revisar quando preço, comissão ou conversão mudarem.", x: "Sem os 3 números a esteira não decide: não sobe o P1." },
        checklist: ["Payout definido", "CPA alvo definido", "ICs por venda (padrão 8) definido"] }),
      step({ ordem: 4, secao: "P1 · Teste de concepts", label: "Concepts com hipótese", kind: "processo", executor_type: "EXTERNAL_TOOL", skill: "angulos-criativos", depende_de: [2, 3],
        contrato: { o: "Montar até 10 concepts (1 ângulo × 1 avatar), 3 anúncios cada, e escrever a hipótese de cada um: o que precisa ser verdade para ele vender.", e: "Ângulos, avatar e hipóteses refutadas das rodadas anteriores.", s: "Concepts nomeados por ângulo e avatar, com hipótese escrita.", p: "Cada concept com 3 anúncios e hipótese; nenhuma hipótese já refutada repetida sem premissa nova.", m: "Concepts prontos por semana.", d: "Ângulos e parâmetros.", f: "Semanal.", x: "Sem hipótese escrita a rodada não ensina: completar antes de subir." },
        checklist: ["Até 10 concepts com 3 anúncios cada", "Hipótese escrita em cada concept", "Placar da rodada anterior consultado"] }),
      step({ ordem: 5, secao: "P1 · Teste de concepts", label: "P1 — Campanha de teste ABO 1-5-3", kind: "meta_ads", executor_type: "HUMAN_OPERATOR", depende_de: [4],
        metrica: { key: "custo_por_ic", meta: "até CPA alvo ÷ ICs por venda", unidade: "moeda" },
        contrato: { o: "Rodar 1 conjunto por concept, verba fixa (referência ~40/conjunto/dia), 2 dias sem mexer.", e: "Concepts com hipótese, link com UTM, pixel com checkout iniciado.", s: "Gasto, checkouts iniciados e vendas por concept no fim do dia 2.", p: "Dia 2 completo com os 3 números de cada concept registrados.", m: "Custo por IC por concept.", d: "Concepts e conta de anúncio.", f: "Semanal.", x: "Sem IC medido não há veredito: conferir o pixel antes de julgar." },
        checklist: ["Campanha no ar com 1 conjunto por concept", "2 dias sem mexer", "Gasto, IC e vendas registrados por concept"] }),
      step({ ordem: 6, secao: "P1 · Teste de concepts", label: "P1 — Veredito e placar de hipóteses", kind: "ia", executor_type: "AI_SKILL", depende_de: [5],
        contrato: { o: "Aplicar o veredito de cada concept (QUALIFICADO, MAIS TEXTOS, MATA, CEDO) com evaluate_scale e montar o placar de hipóteses: confirmada, parcial ou refutada.", e: "Gasto, IC e vendas por concept; parâmetros.", s: "Concepts qualificados para o P2, pedidos de mais textos e placar de hipóteses nas notas.", p: "Todo concept com veredito e toda hipótese com resultado.", m: "Qualificados; custo por qualificado.", d: "Dia 2 do P1 completo.", f: "Fim de cada rodada.", x: "Nenhum qualificado: volta ao P1 com hipóteses novas, não com o mesmo concept." },
        checklist: ["Veredito de cada concept", "Placar de hipóteses registrado", "Qualificados enviados ao P2"] }),
      step({ ordem: 7, secao: "P2 · Rodada de texto", label: "P2 — Rodada ABO 1-5-10", kind: "meta_ads", executor_type: "HUMAN_OPERATOR", depende_de: [6],
        metrica: { key: "cpa", meta: "até o CPA alvo no dia 3", unidade: "moeda" },
        contrato: { o: "Para cada primary text vencedor: 5 conjuntos idênticos, até 10 adformats, 3 dias. Julgar só no dia 3 pelo CPA acumulado.", e: "Concepts qualificados e textos vencedores.", s: "CPA acumulado e veredito por conjunto no dia 3.", p: "Dia 3 completo com APROVADO, ESTENDE ou REPROVADO e cada conjunto como DUPLICA, MANTÉM ou MATA.", m: "CPA acumulado; zona do CPA.", d: "Veredito do P1.", f: "A cada concept qualificado.", x: "REPROVADO volta ao P1 com texto novo; pausar conjunto não mata o concept." },
        checklist: ["5 conjuntos idênticos no ar", "Checkpoint do dia 2 lido (sem decidir)", "Veredito no dia 3"] }),
      step({ ordem: 8, secao: "P3 · Escala", label: "P3 — Escala CBO com bid cap", kind: "meta_ads", executor_type: "HUMAN_OPERATOR", depende_de: [7],
        metrica: { key: "roas", meta: "acima de payout ÷ CPA alvo" },
        contrato: { o: "Escalar os aprovados em CBO perpétuo, 1 conjunto por ângulo, lance inicial = 60% do CPA alvo, teto econômico = 80% do payout.", e: "Concepts aprovados no P2.", s: "Gasto crescendo com o CPA na zona ESCALA ou LUCRATIVA.", p: "Rotina diária registrada: uma mexida por dia (verba ou lance).", m: "Gasto diário; CPA 7 dias por ângulo.", d: "Aprovação no P2.", f: "Diária (rotina de 10 segundos).", x: "Ângulo com CPA acima do payout: REVISA; 7+ dias sem gastar: vai para o P4." },
        checklist: ["Rotina diária: verba ≥ 95% gasta sobe verba ~20%, senão lance ~17%", "Nunca verba e lance no mesmo dia", "Ângulos com 7+ dias sem gasto movidos para o P4"] }),
      step({ ordem: 9, secao: "P4 · Cemitério", label: "P4 — Cemitério CBO 1-1-10 com cost cap", kind: "meta_ads", executor_type: "HUMAN_OPERATOR", depende_de: [8],
        contrato: { o: "Guardar ângulos que escalaram e secaram em campanha permanente com cost cap = 70% do CPA alvo, até 10 ângulos.", e: "Ângulos que saíram do P3.", s: "Vendas baratas ocasionais e ângulos que voltam ao P3.", p: "Campanha montada uma vez, sem mexer; revisão semanal feita.", m: "Gasto e vendas 7 dias por ângulo.", d: "P3.", f: "Revisão semanal.", x: "Gasto zero é o normal; 3 dias seguidos dentro do CPA: volta ao P3." },
        checklist: ["Campanha com cost cap montada", "Revisão semanal dos ângulos", "Ângulos com 3 dias no CPA devolvidos ao P3"] }),
      step({ ordem: 10, secao: "Medição", label: "Revisão semanal da esteira", kind: "ia", executor_type: "AI_SKILL", skill: "analise-criativos-escalados", depende_de: [6, 8],
        metrica: { key: "cpa" },
        contrato: { o: "Fechar a semana: placar de hipóteses, ângulos em cada fase e o próximo lote de concepts a partir das hipóteses confirmadas.", e: "Vereditos do P1 e P2, rotina do P3 e cemitério.", s: "Resumo da semana e próximo lote de concepts.", p: "Resumo registrado e próximo P1 planejado.", m: "CPA e vendas da semana por fase.", d: "P1 e P3.", f: "Semanal.", x: "Semana sem placar: o próximo lote não sai até ter as hipóteses avaliadas." } }),
    ],
  },

  // ───────────── Webinar perpétuo ─────────────
  {
    id: "webinar-perpetuo", nome: "Webinar perpétuo", familia: "webinar_lancamento",
    resumo: "Anúncio → inscrição → lembretes → aula (ao vivo ou gravada com horário) → oferta com prazo → recuperação.",
    quando_usar: "Produto que precisa de demonstração ou quebra de crença; ticket médio.",
    quando_evitar: "Sem aula pronta ou sem oferta definida para o pitch.",
    horizonte: "14 dias para o primeiro ciclo completo.", north_star: "vendas",
    kpis: [
      { key: "inscritos", label: "Inscritos", meta: "ajustar ao orçamento" },
      { key: "cpl", label: "Custo por inscrito", meta: "definir no 1º ciclo", unidade: "moeda" },
      { key: "presenca_live", label: "Presença na aula", meta: "referência inicial: 20% a 35% dos inscritos" },
      { key: "vendas", label: "Vendas por turma", meta: "calibrar no 1º ciclo" },
    ],
    riscos: ["Lembretes em excesso no WhatsApp: risco de bloqueio do número.", "Prazo falso na oferta: perde confiança e pode violar regras de anúncio."],
    fonte: "imphq_funnel_templates:webinar-evergreen",
    steps: [
      step(avatar(1)),
      step(angulos(2, [1])),
      step({ ordem: 3, secao: "Aquisição", label: "Anúncio de inscrição", kind: "meta_ads", executor_type: "HUMAN_OPERATOR", skill: "briefing-gestor-trafego",
        contrato: { o: "Trazer inscrições para a aula de {produto}.", e: "Ângulos e página de inscrição com UTM.", s: "Inscrições com origem.", p: "Custo por inscrito medido e dentro da meta.", m: "CPL; inscrições por dia.", d: "Página de inscrição.", f: "Contínua.", x: "CPL acima da meta por 3 dias: trocar o criativo." }, metrica: { key: "cpl" } }),
      step({ ordem: 4, secao: "Aquisição", label: "Página de inscrição", kind: "captura", executor_type: "AI_SKILL", skill: "lp-persuasiva-v2",
        contrato: { o: "Converter visitante em inscrito com promessa clara da aula.", e: "Tráfego do anúncio.", s: "Lead cadastrado com origem.", p: "Taxa de inscrição medida e lead chegando ao Império.", m: "Taxa de conversão da página.", d: "Tracker; integração de leads.", f: "Revisar a cada ciclo.", x: "Página fora do ar: pausar os anúncios." }, metrica: { key: "inscritos" } }),
      step({ ordem: 5, secao: "Aquecimento", label: "Lembretes até a aula", kind: "whatsapp_sequencia", executor_type: "API_AUTONOMOUS", skill: "webinar-blocks",
        contrato: { o: "Levar o inscrito até a aula: confirmação, D-1, 1 h antes e link na hora.", e: "Lista de inscritos e horário.", s: "Mensagens entregues.", p: "Sequência ativa com limite de envio respeitado.", m: "Presença ÷ inscritos.", d: "Número ou e-mail conectado.", f: "A cada turma.", x: "Falha de envio: no máximo 3 tentativas e pausa." }, metrica: { key: "presenca_live" } }),
      step({ ordem: 6, secao: "Conversão", label: "Aula / webinar", kind: "webinar", executor_type: "HUMAN_OPERATOR", skill: "webinar-blocks",
        contrato: { o: "Ensinar, quebrar crenças e apresentar a oferta de {produto}.", e: "Roteiro com blocos de conteúdo e pitch.", s: "Cliques na oferta.", p: "Aula realizada ou gravação no ar com horário fixo.", m: "Presença; cliques na oferta.", d: "Lembretes; checkout.", f: "Por turma.", x: "Problema técnico: reagendar e avisar os inscritos no mesmo dia." } }),
      step({ ordem: 7, secao: "Conversão", label: "Oferta com prazo real", kind: "checkout", executor_type: "EXTERNAL_TOOL",
        contrato: { o: "Fechar a venda com bônus ou condição que vence de verdade.", e: "Cliques da aula e da sequência.", s: "Vendas com origem.", p: "Checkout ativo e vendas chegando pelo webhook.", m: "Vendas; taxa de conversão de presentes.", d: "Webhook.", f: "Por turma.", x: "Não renovar prazo \"falso\"; se precisar, criar nova condição honesta." }, metrica: { key: "vendas" } }),
      step({ ordem: 8, secao: "Conversão", label: "Replay e recuperação", kind: "replay", executor_type: "API_AUTONOMOUS",
        contrato: { o: "Recuperar quem não assistiu ou não comprou: replay por tempo limitado e 3 toques no carrinho.", e: "Inscritos sem compra; abandonos.", s: "Vendas recuperadas.", p: "Replay no ar e recuperação ativa.", m: "Vendas do replay; recuperadas.", d: "Página de replay; webhook de abandono.", f: "Por turma.", x: "No máximo 3 toques por pessoa." }, metrica: { key: "recuperadas" } }),
      step({ ordem: 9, secao: "Medição", label: "Análise da turma", kind: "ia", executor_type: "AI_SKILL", skill: "analise-criativos-escalados",
        contrato: { o: "Comparar a turma com a anterior: CPL, presença, conversão e receita; escolher 1 coisa para mudar.", e: "Leads, presença, vendas e gasto.", s: "Relatório da turma e o próximo experimento.", p: "Relatório registrado e experimento criado.", m: "Receita por inscrito.", d: "Dados da turma.", f: "Por turma.", x: "Mudar uma variável por vez." }, metrica: { key: "roas" }, depende_de: [3, 7] }),
    ],
  },

  // ───────────── Lançamento pago ─────────────
  {
    id: "lancamento-pago", nome: "Lançamento pago", familia: "webinar_lancamento",
    resumo: "Captação paga de leads → grupo/lista → evento de 3 a 4 aulas (CPLs) → abertura de carrinho com prazo → fechamento.",
    quando_usar: "Produto de ticket mais alto, expert com conteúdo forte, janela para concentrar verba.",
    quando_evitar: "Sem caixa para captação concentrada ou sem conteúdo do evento pronto.",
    horizonte: "3 a 4 semanas por ciclo.", north_star: "receita",
    kpis: [
      { key: "leads", label: "Leads captados", meta: "definir pelo objetivo de receita" },
      { key: "cpl", label: "Custo por lead", meta: "definir no planejamento", unidade: "moeda" },
      { key: "vendas", label: "Vendas no carrinho", meta: "referência inicial: 1% a 3% dos leads" },
      { key: "roas", label: "ROAS do lançamento", meta: "acima de 2 (referência)" },
    ],
    riscos: ["Grupo de WhatsApp sem moderação vira spam.", "Carrinho reaberto sem motivo real desgasta a base."],
    fonte: "imphq_funnel_templates:lancamento-classico",
    steps: [
      step(avatar(1)),
      step({ ordem: 2, secao: "Preparação", label: "Promessa e roteiro do evento", kind: "doc", executor_type: "AI_SKILL", skill: "imperius-copy-strategist",
        contrato: { o: "Definir a grande promessa, o mecanismo e o roteiro das aulas (problema → solução → oferta).", e: "Avatar, mecanismo, provas.", s: "Roteiro das aulas e copy de captação.", p: "Roteiro aprovado e copy de captação pronta.", m: "—", d: "Avatar.", f: "Por lançamento.", x: "Sem promessa clara, não iniciar a captação." }, depende_de: [1] }),
      step({ ordem: 3, secao: "Captação", label: "Anúncios de captação", kind: "meta_ads", executor_type: "HUMAN_OPERATOR", skill: "briefing-gestor-trafego",
        contrato: { o: "Captar leads no período definido com orçamento concentrado.", e: "Criativos e página de captura.", s: "Leads com origem.", p: "CPL dentro do planejado.", m: "CPL; leads por dia.", d: "Página de captura.", f: "Durante a captação.", x: "CPL 30% acima do planejado: trocar criativo antes de aumentar verba." }, metrica: { key: "cpl" } }),
      step({ ordem: 4, secao: "Captação", label: "Página de captura", kind: "captura", executor_type: "AI_SKILL", skill: "lp-persuasiva-v2",
        contrato: { o: "Converter visitante em lead do evento.", e: "Tráfego da captação.", s: "Lead no Império e no grupo/lista.", p: "Taxa de conversão medida.", m: "Conversão da página.", d: "Tracker; grupo ou lista.", f: "Durante a captação.", x: "Página fora do ar: pausar anúncios." }, metrica: { key: "leads" } }),
      step({ ordem: 5, secao: "Evento", label: "Grupo ou lista de aquecimento", kind: "grupo_whatsapp", executor_type: "HUMAN_OPERATOR",
        contrato: { o: "Reunir os leads e manter a atenção até as aulas.", e: "Leads captados.", s: "Membros ativos no grupo/lista.", p: "Moderação e cronograma de mensagens definidos.", m: "Leads → membros.", d: "Página de obrigado com o link do grupo.", f: "Diária durante o evento.", x: "Link do grupo cheio: trocar na página de obrigado." } }),
      step({ ordem: 6, secao: "Evento", label: "Aulas do evento", kind: "live", executor_type: "HUMAN_OPERATOR", skill: "webinar-blocks",
        contrato: { o: "Entregar 3 a 4 aulas que levam à abertura do carrinho.", e: "Roteiro do evento.", s: "Audiência engajada e lista de interessados.", p: "Aulas entregues no horário.", m: "Presença por aula.", d: "Grupo/lista.", f: "Por lançamento.", x: "Aula com problema: publicar gravação no mesmo dia." }, metrica: { key: "presenca_live" } }),
      step({ ordem: 7, secao: "Carrinho", label: "Abertura de carrinho", kind: "checkout", executor_type: "EXTERNAL_TOOL",
        contrato: { o: "Vender com prazo real e bônus para quem entra cedo.", e: "Audiência das aulas.", s: "Vendas com origem.", p: "Checkout ativo, webhook funcionando, prazo comunicado.", m: "Vendas por dia de carrinho.", d: "Webhook.", f: "Por lançamento.", x: "Checkout com erro: avisar no grupo e corrigir antes de seguir com anúncios." }, metrica: { key: "vendas" } }),
      step({ ordem: 8, secao: "Carrinho", label: "Recuperação e fechamento", kind: "recuperacao", executor_type: "API_AUTONOMOUS",
        contrato: { o: "Recuperar boletos, pix e abandonos e fazer a última chamada.", e: "Pendências e abandonos.", s: "Vendas recuperadas.", p: "Rotina ativa até o fechamento.", m: "Recuperadas.", d: "Webhook de abandono.", f: "Durante o carrinho.", x: "No máximo 3 toques por pessoa." }, metrica: { key: "recuperadas" } }),
      step({ ordem: 9, secao: "Medição", label: "Debrief do lançamento", kind: "ia", executor_type: "AI_SKILL", skill: "analise-criativos-escalados",
        contrato: { o: "Fechar números do lançamento (CPL, conversão, ROAS) e listar o que repetir e o que mudar.", e: "Gasto, leads, presença e vendas.", s: "Debrief com 3 decisões para o próximo.", p: "Debrief registrado.", m: "ROAS; receita por lead.", d: "Dados completos.", f: "Por lançamento.", x: "Dado faltando: registrar a lacuna em vez de estimar." }, metrica: { key: "roas" }, depende_de: [3, 7] }),
    ],
  },

  // ───────────── Lançamento gratuito ─────────────
  {
    id: "lancamento-gratuito", nome: "Lançamento gratuito (semente / interno)", familia: "webinar_lancamento",
    resumo: "Lançamento para a base própria (seguidores, lista, grupos) sem verba de anúncio: validar oferta e gerar caixa.",
    quando_usar: "Validar produto novo, base própria aquecida, sem orçamento de tráfego.",
    quando_evitar: "Base pequena ou fria: primeiro construir audiência (canal orgânico).",
    horizonte: "2 a 3 semanas.", north_star: "vendas",
    kpis: [
      { key: "leads", label: "Interessados", meta: "10% da base ativa (referência)" },
      { key: "vendas", label: "Vendas", meta: "validar com as primeiras 10 vendas" },
    ],
    riscos: ["Oferta sem validação: começar com pré-venda e entrega simples."],
    fonte: null,
    steps: [
      step(avatar(1)),
      step({ ordem: 2, secao: "Preparação", label: "Pesquisa e oferta semente", kind: "doc", executor_type: "AI_SKILL", skill: "escavador-desejos",
        contrato: { o: "Descobrir o desejo mais forte da base e montar uma oferta simples de validar.", e: "Comentários, conversas e respostas da base.", s: "Oferta semente com preço de entrada.", p: "Oferta escrita e validada com 5 conversas.", m: "Respostas da pesquisa.", d: "Base ativa.", f: "Por lançamento.", x: "Sem resposta da base, voltar ao canal orgânico antes de lançar." }, depende_de: [1] }),
      step({ ordem: 3, secao: "Aquecimento", label: "Conteúdo de aquecimento", kind: "reels", executor_type: "AI_SKILL", skill: "organic-reels-factory",
        contrato: { o: "Aquecer a base com conteúdo sobre o problema e a promessa.", e: "Oferta semente e avatar.", s: "Posts com chamada para a lista de interesse.", p: "Sequência de posts publicada.", m: "Views; comentários.", d: "Canal ativo.", f: "Diária no aquecimento.", x: "Post com desempenho muito baixo: trocar o gancho, não o tema." }, metrica: { key: "views_conteudo" } }),
      step({ ordem: 4, secao: "Aquecimento", label: "Lista de interesse", kind: "captura", executor_type: "AI_SKILL", skill: "lp-persuasiva-v2",
        contrato: { o: "Separar quem tem interesse real para a abertura.", e: "Tráfego do conteúdo e do link na bio.", s: "Lista de interessados.", p: "Página no ar com tracker e lead chegando ao Império.", m: "Interessados.", d: "Link na bio com UTM.", f: "Durante o aquecimento.", x: "Página fora do ar: trocar o link da bio na hora." }, metrica: { key: "leads" } }),
      step({ ordem: 5, secao: "Carrinho", label: "Abertura para a lista", kind: "whatsapp_sequencia", executor_type: "API_AUTONOMOUS",
        contrato: { o: "Abrir o carrinho primeiro para a lista e depois para a base.", e: "Lista de interessados.", s: "Vendas.", p: "Mensagens enviadas com limite respeitado.", m: "Vendas da lista.", d: "Número conectado; checkout.", f: "Por lançamento.", x: "No máximo 3 falhas de envio antes de pausar." } }),
      step({ ordem: 6, secao: "Carrinho", label: "Checkout da oferta semente", kind: "checkout", executor_type: "EXTERNAL_TOOL",
        contrato: { o: "Receber as primeiras vendas com origem.", e: "Cliques da lista e dos posts.", s: "Vendas no Império.", p: "Webhook funcionando.", m: "Vendas.", d: "Webhook.", f: "Por lançamento.", x: "Venda sem origem: marcar para conferência." }, metrica: { key: "vendas" } }),
      step({ ordem: 7, secao: "Medição", label: "Validação da oferta", kind: "ia", executor_type: "AI_SKILL",
        contrato: { o: "Decidir se a oferta vira produto perpétuo (ads/X1/webinar) com base nas vendas e objeções.", e: "Vendas, conversas e objeções.", s: "Decisão: escalar, ajustar ou abandonar.", p: "Decisão registrada.", m: "Conversão da lista.", d: "Dados do lançamento.", f: "Por lançamento.", x: "Menos de 10 vendas: tratar como sinal, não como validação." }, depende_de: [6] }),
    ],
  },

  // ───────────── Canal orgânico ─────────────
  {
    id: "canal-organico", nome: "Canal orgânico ({plataforma})", familia: "organico",
    resumo: "Pedido de canal ponta a ponta: minerar, definir persona e linha editorial, produzir em série, publicar, link na bio com UTM, comentário-palavra → conversa, medir.",
    quando_usar: "Construir audiência própria para {projeto}, baratear aquisição e alimentar X1 e lançamentos.",
    quando_evitar: "Sem capacidade de publicar com frequência por pelo menos 30 dias.",
    horizonte: "30 dias para o primeiro veredito.", north_star: "conversas_x1",
    kpis: [
      { key: "posts_publicados", label: "Posts publicados", meta: "1 por dia (referência)" },
      { key: "views_conteudo", label: "Visualizações", meta: "crescente semana a semana" },
      { key: "cliques_bio", label: "Cliques no link da bio", meta: "medir na 1ª semana" },
      { key: "conversas_x1", label: "Conversas vindas do canal", meta: "medir na 1ª semana" },
    ],
    riscos: ["Conta restrita por automação: respeitar limite diário e aquecimento.", "Conteúdo copiado com marca de terceiros."],
    fonte: null,
    steps: [
      step({ ordem: 1, secao: "Planejamento", label: "Mineração de referências ({plataforma})", kind: "doc", executor_type: "AI_SKILL", skill: "funnel-hacking-supremo-v2",
        contrato: { o: "Achar os perfis e vídeos que mais crescem no nicho de {produto} em {plataforma} e o padrão por trás deles.", e: "Nicho, avatar, concorrentes.", s: "Lista de 20 referências com gancho, formato e chamada.", p: "20 referências classificadas por formato.", m: "Referências mineradas.", d: "Avatar.", f: "Mensal.", x: "Não copiar: registrar só o padrão." }, depende_de: [] }),
      step({ ordem: 2, secao: "Planejamento", label: "Persona e linha editorial", kind: "doc", executor_type: "AI_SKILL", skill: "avatar-vibe-extractor",
        contrato: { o: "Definir quem fala (persona), o tom e 3 a 5 pilares de conteúdo.", e: "Referências mineradas e avatar.", s: "Guia da persona e pilares.", p: "Guia aprovado.", m: "—", d: "Mineração.", f: "Revisar a cada 30 dias.", x: "Persona que fingir ser pessoa real sem aviso: ajustar (ex.: \"personagem de IA\" na bio)." } }),
      step({ ordem: 3, secao: "Planejamento", label: "Conta em {plataforma} e link na bio", kind: "instagram", executor_type: "HUMAN_OPERATOR",
        contrato: { o: "Criar ou ajustar a conta {conta}, aquecer e colocar o link da bio com UTM própria (utm_source={plataforma}, utm_medium=bio).", e: "Persona e destino (quiz, página ou X1).", s: "Conta pronta com link medido.", p: "Conta aquecida e link da bio chegando ao Império com UTM de bio.", m: "Cliques no link da bio.", d: "Destino com tracker do Império.", f: "Revisar o link a cada mudança de oferta.", x: "Conta restrita: pausar publicações nela." }, metrica: { key: "cliques_bio" }, checklist: ["Conta criada e aquecida", "Link da bio com utm_medium=bio", "Destino com tracker"] }),
      step({ ordem: 4, secao: "Produção", label: "Roteiros em série", kind: "doc", executor_type: "AI_SKILL", skill: "organic-reels-factory",
        contrato: { o: "Escrever roteiros por pilar com gancho de 0–3 s e chamada para comentar a palavra.", e: "Linha editorial e referências.", s: "7 roteiros por semana.", p: "Roteiros da semana aprovados.", m: "Roteiros prontos.", d: "Persona e pilares.", f: "Semanal.", x: "Roteiro sem chamada não segue para produção." }, depende_de: [2] }),
      step({ ordem: 5, secao: "Produção", label: "Produção dos vídeos", kind: "reels", executor_type: "EXTERNAL_TOOL", skill: "pipeline-video-viral",
        contrato: { o: "Gerar os vídeos em série a partir dos roteiros (ver ferramentas: Remotion, FFmpeg).", e: "Roteiros aprovados.", s: "Vídeos prontos na biblioteca de conteúdo.", p: "Vídeos da semana na fila de publicação.", m: "Vídeos produzidos.", d: "Roteiros.", f: "Semanal.", x: "Falha na geração: entregar roteiro e prompt para produção manual." } }),
      step({ ordem: 6, secao: "Publicação", label: "Publicação com aprovação", kind: "processo", executor_type: "API_AUTONOMOUS",
        contrato: { o: "Publicar pela esteira (GeeLark) respeitando o limite diário da conta, só com vídeo aprovado.", e: "Vídeos aprovados e calendário.", s: "Posts publicados com link e UTM do post.", p: "Posts publicados no horário e registrados em imphq_content_posts.", m: "Posts publicados.", d: "Conta e aparelho no GeeLark.", f: "Diária.", x: "3 falhas seguidas na conta: pausar e avisar." }, metrica: { key: "posts_publicados" } }),
      step({ ordem: 7, secao: "Conversa", label: "Comentário com a palavra → DM", kind: "lead", executor_type: "API_AUTONOMOUS",
        contrato: { o: "Quem comenta a palavra recebe DM automática e entra no X1 de {produto}.", e: "Comentários dos posts.", s: "Conversas abertas com origem do post.", p: "Gatilho ativo e DM saindo sem erro.", m: "Comentários → conversas.", d: "Integração de DM (ex.: Zernio) conectada à conta.", f: "Contínua.", x: "Erro de envio: no máximo 3 tentativas e pausa." }, metrica: { key: "conversas_x1" } }),
      step({ ordem: 8, secao: "Medição", label: "Métricas do canal", kind: "ia", executor_type: "AI_SKILL",
        contrato: { o: "Medir posts, views, seguidores, cliques na bio e conversas por pilar; escolher o próximo experimento.", e: "imphq_content_metrics_daily e eventos com UTM de bio.", s: "Relatório semanal e 1 experimento novo.", p: "Relatório da semana registrado.", m: "Views por post; conversas por semana.", d: "Coleta de métricas da esteira.", f: "Semanal.", x: "Sem métricas coletadas, a decisão fica pendente." }, metrica: { key: "views_conteudo" }, depende_de: [6, 7] }),
    ],
  },

  // ───────────── SEO e conteúdo ─────────────
  {
    id: "seo-conteudo", nome: "SEO e conteúdo", familia: "seo",
    resumo: "Saúde técnica do site, pesquisa de palavras-chave em clusters, páginas pilares e artigos, links internos e medição no Search Console.",
    quando_usar: "Projeto com site próprio e horizonte de meses; demanda de busca para o problema do avatar.",
    quando_evitar: "Página usada só para anúncio com prazo curto.",
    horizonte: "60 a 90 dias para os primeiros sinais.", north_star: "seo_cliques",
    kpis: [
      { key: "seo_saude", label: "Saúde técnica", meta: "acima de 90%", unidade: "percentual" },
      { key: "seo_impressoes", label: "Impressões", meta: "crescente mês a mês" },
      { key: "seo_cliques", label: "Cliques orgânicos", meta: "crescente mês a mês" },
    ],
    riscos: ["Conteúdo em massa sem qualidade: risco de rebaixamento.", "Promessas de saúde em artigos: revisar compliance."],
    fonte: null,
    steps: [
      step({ ordem: 1, secao: "Base técnica", label: "Auditoria técnica do site", kind: "seo", executor_type: "AI_SKILL",
        contrato: { o: "Checar indexação, título, meta descrição, H1, canonical, sitemap, robots, velocidade e dados estruturados das páginas de {projeto}.", e: "URLs do site.", s: "Lista de correções por prioridade.", p: "Auditoria registrada e itens críticos corrigidos.", m: "Saúde técnica (% aprovado).", d: "Acesso ao repositório do site.", f: "Mensal.", x: "Página crítica fora do índice: corrigir antes de produzir conteúdo." }, metrica: { key: "seo_saude", meta: "acima de 90%" }, depende_de: [] }),
      step({ ordem: 2, secao: "Base técnica", label: "Search Console ligado", kind: "google_analytics", executor_type: "HUMAN_OPERATOR",
        contrato: { o: "Verificar o domínio no Search Console e ligar ao Império para medir impressões, cliques e posição.", e: "Acesso ao DNS ou ao site.", s: "Dados diários de busca no Império.", p: "Domínio verificado e dados chegando.", m: "Impressões e cliques.", d: "Acesso de quem administra o domínio.", f: "Uma vez; conferir mensalmente.", x: "Sem acesso: registrar e seguir só com a auditoria técnica." }, metrica: { key: "seo_impressoes" } }),
      step({ ordem: 3, secao: "Estratégia", label: "Clusters de palavras-chave", kind: "doc", executor_type: "AI_SKILL", skill: "niche-research",
        contrato: { o: "Agrupar as buscas do avatar em clusters (problema, solução, produto) e escolher os pilares.", e: "Avatar, concorrentes e ferramentas de palavra-chave.", s: "Mapa de clusters com intenção e prioridade.", p: "3 clusters escolhidos com páginas pilares definidas.", m: "Clusters priorizados.", d: "Avatar.", f: "Trimestral.", x: "Sem dado de volume, priorizar pela intenção de compra." }, depende_de: [] }),
      step({ ordem: 4, secao: "Produção", label: "Páginas pilares", kind: "pagina_vendas", executor_type: "AI_SKILL", skill: "lp-persuasiva-v2",
        contrato: { o: "Criar ou ajustar a página pilar de cada cluster, com chamada para a oferta.", e: "Clusters e oferta.", s: "Páginas pilares publicadas.", p: "Pilares publicadas com dados estruturados e links internos.", m: "Impressões por pilar.", d: "Clusters; auditoria técnica.", f: "Por cluster.", x: "Pilar com promessa de saúde sem revisão não publica." } }),
      step({ ordem: 5, secao: "Produção", label: "Artigos do cluster", kind: "blog", executor_type: "AI_SKILL", skill: "rebel-copy",
        contrato: { o: "Publicar artigos que respondem às buscas do cluster e apontam para a pilar.", e: "Clusters e pilar.", s: "Artigos publicados e interligados.", p: "4 artigos por cluster publicados.", m: "Cliques por artigo.", d: "Páginas pilares.", f: "Semanal.", x: "Artigo sem revisão humana não publica." }, metrica: { key: "seo_cliques" } }),
      step({ ordem: 6, secao: "Medição", label: "Acompanhamento de busca", kind: "ia", executor_type: "AI_SKILL",
        contrato: { o: "Ler impressões, cliques e posição por cluster e decidir o que atualizar, expandir ou cortar.", e: "Dados do Search Console e da auditoria.", s: "Plano do mês.", p: "Relatório mensal registrado.", m: "Cliques e posição por cluster.", d: "Search Console ligado.", f: "Mensal.", x: "Sem Search Console, usar só a auditoria técnica e marcar a lacuna." }, metrica: { key: "seo_cliques" }, depende_de: [2, 5] }),
    ],
  },
];
