ALTER TABLE imphq_tracking_links ADD COLUMN IF NOT EXISTS data_inicio TIMESTAMPTZ;
ALTER TABLE imphq_tracking_links ADD COLUMN IF NOT EXISTS data_fim TIMESTAMPTZ;
ALTER TABLE imphq_kb ADD COLUMN IF NOT EXISTS parent_key TEXT;
ALTER TABLE imphq_kb ADD COLUMN IF NOT EXISTS is_custom BOOLEAN DEFAULT false;
ALTER TABLE imphq_kb ADD COLUMN IF NOT EXISTS doc_ids TEXT[];