
ALTER TABLE imphq_ads_spend ADD COLUMN IF NOT EXISTS nivel_veiculacao TEXT;
ALTER TABLE imphq_ads_spend ADD COLUMN IF NOT EXISTS checkouts_iniciados INT DEFAULT 0;
ALTER TABLE imphq_ads_spend ADD COLUMN IF NOT EXISTS cpm NUMERIC DEFAULT 0;
ALTER TABLE imphq_ads_spend ADD COLUMN IF NOT EXISTS stop_rate NUMERIC DEFAULT 0;
ALTER TABLE imphq_ads_spend ADD COLUMN IF NOT EXISTS cpck NUMERIC DEFAULT 0;
