ALTER TABLE public.imphq_ads_spend
  ADD COLUMN IF NOT EXISTS init_checkout INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS add_to_cart INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS landing_page_views INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS video_3s_views INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS video_thruplay INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS link_clicks INTEGER DEFAULT 0;